[tools]
java = "temurin-25.0.4+7.0.LTS"
gradle = "9.8.0"
node = "24.21.0"
pnpm = "10.34.6"
dotnet = "8.0.425"
python = "3.13"
"github:astral-sh/uv" = "0.12.21"
"ubi:oasdiff/oasdiff" = "1.32.1"
"pipx:reuse" = { version = "6.2.0", extras = "charset-normalizer" }
