using System.Globalization;
using System.Text;
using YamlDotNet.Serialization;

// Build-time generator: reads the bundled OpenAPI spec and emits three derived
// source files. Mirrors the Kotlin build's generateProblemSlugs, generateValidation,
// and generateContractVersionResource tasks (client/build.gradle.kts).

if (args.Length != 2)
{
    Console.Error.WriteLine("usage: Epistola.Client.Gen <openapi.yaml> <output-dir>");
    return 1;
}

var specPath = args[0];
var outDir = args[1];

if (!File.Exists(specPath))
{
    Console.Error.WriteLine($"spec not found: {specPath}");
    return 1;
}

Directory.CreateDirectory(outDir);

var deserializer = new DeserializerBuilder().Build();
var root = (IDictionary<object, object>)deserializer.Deserialize<object>(File.ReadAllText(specPath))!;

WriteFile(outDir, "ContractVersion.g.cs", GenerateContractVersion(root));
WriteFile(outDir, "KnownProblemSlugs.g.cs", GenerateProblemSlugs(root));
WriteFile(outDir, "ModelValidation.g.cs", GenerateModelValidation(root));

return 0;

static void WriteFile(string dir, string name, string content)
{
    var path = Path.Combine(dir, name);
    File.WriteAllText(path, content);
    Console.WriteLine($"    wrote {name}");
}

// --- ContractVersion (from info.version) ---
static string GenerateContractVersion(IDictionary<object, object> root)
{
    var info = (IDictionary<object, object>)root["info"];
    var version = (string)info["version"];
    return $$"""
        // <auto-generated>Generated from the OpenAPI spec's info.version — do not edit.</auto-generated>
        namespace Epistola.Client.Generated;

        /// <summary>The Epistola contract version this client library was built against.</summary>
        internal static class ContractVersion
        {
            internal const string Version = "{{version}}";
        }

        """;
}

// --- KnownProblemSlugs (from the x-problem-types registry) ---
static string GenerateProblemSlugs(IDictionary<object, object> root)
{
    if (!root.TryGetValue("x-problem-types", out var registryObj) || registryObj is not IDictionary<object, object> registry)
    {
        throw new InvalidOperationException(
            "bundled spec has no x-problem-types extension — KnownProblemSlugs cannot be generated");
    }

    if (!registry.TryGetValue("base", out var baseObj) || baseObj is not string baseUri)
    {
        throw new InvalidOperationException("x-problem-types.base is missing from the bundled spec");
    }

    var types = registry.TryGetValue("types", out var t) && t is IList<object> list
        ? list.Cast<IDictionary<object, object>>().ToList()
        : new List<IDictionary<object, object>>();

    if (types.Count < 8)
    {
        throw new InvalidOperationException(
            $"x-problem-types lists only {types.Count} problem types (expected at least 8) — was the registry truncated?");
    }

    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated>Generated from the OpenAPI spec's x-problem-types extension — do not edit.</auto-generated>");
    sb.AppendLine("namespace Epistola.Client.Error;");
    sb.AppendLine();
    sb.AppendLine("/// <summary>Base URI from the spec's x-problem-types registry; must equal <see cref=\"ProblemTypes.TypeBase\"/>.</summary>");
    sb.AppendLine($"internal static class GeneratedProblemType");
    sb.AppendLine("{");
    sb.AppendLine($"    internal const string Base = \"{baseUri}\";");
    sb.AppendLine("}");
    sb.AppendLine();
    sb.AppendLine("/// <summary>");
    sb.AppendLine("/// The canonical problem <c>type</c> slugs the Epistola API emits, from the contract's");
    sb.AppendLine("/// error-type registry (the spec's <c>x-problem-types</c> extension / <c>docs/error-types.md</c>).");
    sb.AppendLine("///");
    sb.AppendLine("/// These are convenience constants for <c>switch (e.TypeSlug)</c>. <c>TypeSlug</c> is deliberately a");
    sb.AppendLine("/// plain <c>string?</c> (not an enum) so the API can introduce new problem types without forcing a");
    sb.AppendLine("/// client release — always keep a <c>default</c> branch.");
    sb.AppendLine("/// </summary>");
    sb.AppendLine("public static class KnownProblemSlugs");
    sb.AppendLine("{");
    var first = true;
    foreach (var entry in types)
    {
        var slug = (string)entry["slug"];
        var status = entry.TryGetValue("status", out var s) ? s?.ToString() : null;
        var description = entry.TryGetValue("description", out var d) ? d?.ToString() ?? "" : "";
        description = System.Text.RegularExpressions.Regex.Replace(description, "\\s+", " ").Trim();
        var constName = slug.ToUpperInvariant().Replace('-', '_');
        if (!first) sb.AppendLine();
        first = false;
        sb.AppendLine($"    /// <summary>{status} — {EscapeXml(description)}</summary>");
        sb.AppendLine($"    public const string {constName} = \"{slug}\";");
    }
    sb.AppendLine("}");
    return sb.ToString();
}

// --- ModelValidation (from schema constraints) ---
static string GenerateModelValidation(IDictionary<object, object> root)
{
    var components = (IDictionary<object, object>)root["components"];
    var schemas = (IDictionary<object, object>)components["schemas"];

    var methods = new List<string>();

    foreach (var (schemaNameObj, schemaDefObj) in schemas)
    {
        if (schemaDefObj is not IDictionary<object, object> schema) continue;
        if (!schema.TryGetValue("type", out var typeVal) || typeVal as string != "object") continue;
        if (!schema.TryGetValue("properties", out var propsObj) || propsObj is not IDictionary<object, object> properties) continue;

        var schemaName = (string)schemaNameObj;
        var required = schema.TryGetValue("required", out var r) && r is IList<object> reqList
            ? reqList.Select(x => x.ToString()!).ToHashSet()
            : new HashSet<string>();

        var fieldBlocks = new List<string>();

        foreach (var (propNameObj, propDefObj) in properties)
        {
            if (propDefObj is not IDictionary<object, object> prop) continue;
            if (prop.ContainsKey("$ref")) continue; // those types have their own Validate()

            var propName = (string)propNameObj;
            var (baseType, isNullableType) = ResolveType(prop);
            if (baseType == null) continue;
            var isNullable = !required.Contains(propName) || isNullableType;
            var member = Pascal(propName);

            var checks = new List<string>();
            switch (baseType)
            {
                case "string":
                    var pattern = prop.TryGetValue("pattern", out var pat) ? pat as string : null;
                    var minLen = IntOrNull(prop, "minLength");
                    var maxLen = IntOrNull(prop, "maxLength");
                    if (minLen != null && maxLen != null)
                        checks.Add($"if (v.Length < {minLen} || v.Length > {maxLen}) throw new System.ArgumentException(\"{propName}: length must be between {minLen} and {maxLen}\");");
                    else if (minLen != null)
                        checks.Add($"if (v.Length < {minLen}) throw new System.ArgumentException(\"{propName}: length must be at least {minLen}\");");
                    else if (maxLen != null)
                        checks.Add($"if (v.Length > {maxLen}) throw new System.ArgumentException(\"{propName}: length must be at most {maxLen}\");");
                    if (pattern != null)
                    {
                        var esc = EscapeCsString(pattern);
                        checks.Add($"if (!System.Text.RegularExpressions.Regex.IsMatch(v, \"{esc}\")) throw new System.ArgumentException(\"{propName}: must match pattern {esc}\");");
                    }
                    break;
                case "integer":
                    var min = IntOrNull(prop, "minimum");
                    var max = IntOrNull(prop, "maximum");
                    if (min != null && max != null)
                        checks.Add($"if (v < {min} || v > {max}) throw new System.ArgumentException(\"{propName}: must be between {min} and {max}\");");
                    else if (min != null)
                        checks.Add($"if (v < {min}) throw new System.ArgumentException(\"{propName}: must be at least {min}\");");
                    else if (max != null)
                        checks.Add($"if (v > {max}) throw new System.ArgumentException(\"{propName}: must be at most {max}\");");
                    break;
                case "array":
                    var minItems = IntOrNull(prop, "minItems");
                    if (minItems != null)
                        checks.Add($"if (v.Count < {minItems}) throw new System.ArgumentException(\"{propName}: must have at least {minItems} item(s)\");");
                    break;
            }

            if (checks.Count == 0) continue;

            var body = string.Join("\n", checks.Select(c => "            " + c));
            // Guard against null for reference-typed members (strings/lists) and
            // Nullable<T> for value types. The null check covers both.
            fieldBlocks.Add(
                $"        {{\n" +
                $"            var v = model.{member};\n" +
                (isNullable ? "            if (v != null)\n            {\n" + Indent(body) + "\n            }\n" : body + "\n") +
                $"        }}");
        }

        if (fieldBlocks.Count == 0) continue;

        methods.Add(
            $"    /// <summary>Validates {schemaName} against the contract's schema constraints; returns it on success.</summary>\n" +
            $"    public static Model.{schemaName} Validate(this Model.{schemaName} model)\n" +
            $"    {{\n" +
            string.Join("\n", fieldBlocks) + "\n" +
            $"        return model;\n" +
            $"    }}");
    }

    if (methods.Count == 0)
    {
        throw new InvalidOperationException(
            "GenerateModelValidation produced no validators — either the spec lost all its constraints " +
            "or the schema-walking code no longer matches the spec structure");
    }

    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated>Generated from OpenAPI schema constraints — do not edit.</auto-generated>");
    sb.AppendLine("namespace Epistola.Client.Validation;");
    sb.AppendLine();
    sb.AppendLine("/// <summary>");
    sb.AppendLine("/// Fail-fast <c>Validate()</c> extension methods enforcing the string/number/array");
    sb.AppendLine("/// constraints declared on the contract's request/response models.");
    sb.AppendLine("/// </summary>");
    sb.AppendLine("public static class ModelValidation");
    sb.AppendLine("{");
    sb.AppendLine(string.Join("\n\n", methods));
    sb.AppendLine("}");
    return sb.ToString();
}

static (string? baseType, bool isNullableType) ResolveType(IDictionary<object, object> prop)
{
    if (!prop.TryGetValue("type", out var typeVal)) return (null, false);
    switch (typeVal)
    {
        case string s:
            return (s, false);
        case IList<object> list:
            var nonNull = list.Select(x => x.ToString()).FirstOrDefault(x => x != "null");
            return (nonNull, list.Any(x => x.ToString() == "null"));
        default:
            return (null, false);
    }
}

static int? IntOrNull(IDictionary<object, object> prop, string key)
{
    if (!prop.TryGetValue(key, out var v) || v == null) return null;
    return int.TryParse(v.ToString(), NumberStyles.Integer, CultureInfo.InvariantCulture, out var i) ? i : null;
}

// PascalCase a spec property name to match the OpenAPI C# generator's member naming.
static string Pascal(string name)
{
    var parts = name.Split(new[] { '_', '-', ' ' }, StringSplitOptions.RemoveEmptyEntries);
    var sb = new StringBuilder();
    foreach (var part in parts)
    {
        sb.Append(char.ToUpperInvariant(part[0]));
        if (part.Length > 1) sb.Append(part.Substring(1));
    }
    return sb.ToString();
}

static string EscapeCsString(string s) => s
    .Replace("\\", "\\\\")
    .Replace("\"", "\\\"");

static string EscapeXml(string s) => s
    .Replace("&", "&amp;")
    .Replace("<", "&lt;")
    .Replace(">", "&gt;");

static string Indent(string block) => string.Join("\n", block.Split('\n').Select(l => l.Length == 0 ? l : "    " + l));
