// SPDX-FileCopyrightText: Epistola Nederland B.V.
//
// SPDX-License-Identifier: EUPL-1.2

// The shared wire-protocol logic. This build exists so the logic has an isolated home and its own
// test suite; the artifact is NOT published. Each consumer compiles `src/main/java` into its own
// jar instead (see `epistolaProtocolSources` in their builds), which keeps the published surface at
// four artifacts and costs a consumer nothing at resolution time.
//
// That means all three consumer jars carry app.epistola.protocol.* at the same FQCN. It is safe
// because an application takes one of them, not two: it is a Spring client, or a Jakarta client,
// or an implementation of the API. Two on one classpath would be a split package — harmless on a
// flat classpath since they are released in lockstep, rejected under JPMS or OSGi. If that ever
// stops holding, relocate the package per consumer rather than publishing this.

plugins {
    `java-library`
}

description = "Epistola wire-protocol logic in Java, compiled into the JVM clients and server stubs"

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(libs.versions.java.toolchain.get().toInt()))
    }
}

tasks.withType<JavaCompile>().configureEach {
    // Matches the Jakarta client, the lowest floor among the consumers.
    options.release.set(17)
    options.encoding = "UTF-8"
}

// No dependencies, deliberately. These sources are compiled into every consumer's artifact — the
// Kotlin client into a Spring application, the Jakarta client into a WAR — so anything added here
// is added to all of them. ProtocolContractTest asserts it.
dependencies {
    // Nullness annotations, compileOnly: they are what lets Kotlin consumers see real nullable
    // types instead of platform types across this Java boundary, and nothing needs them at
    // runtime — an absent annotation class is simply ignored when the class is loaded.
    compileOnly(libs.jspecify)

    testImplementation(libs.jspecify)
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.platform.launcher)
}

tasks.test {
    useJUnitPlatform()
    testLogging {
        events("failed")
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
    }
}

// --- Dependency hygiene ---
val dependencyReportDir = layout.buildDirectory.dir("generated-test-resources")

val generateDependencyReport by tasks.registering {
    description = "Records the resolved runtime classpath for ProtocolHasNoDependenciesTest"
    group = "verification"

    val runtimeClasspath = configurations.named("runtimeClasspath")
    val outDir = dependencyReportDir
    outputs.dir(outDir)

    doLast {
        val outFile = outDir.get().file("runtime-dependencies.txt").asFile
        outFile.parentFile.mkdirs()
        outFile.writeText(
            buildString {
                appendLine("# Generated by the generateDependencyReport task — do not edit.")
                runtimeClasspath.get().resolvedConfiguration.resolvedArtifacts
                    .map { with(it.moduleVersion.id) { "$group:$name:$version" } }
                    .sorted()
                    .distinct()
                    .forEach { appendLine(it) }
            },
        )
    }
}

sourceSets {
    test {
        resources.srcDir(dependencyReportDir)
    }
}

tasks.processTestResources {
    dependsOn(generateDependencyReport)
}

tasks.javadoc {
    (options as StandardJavadocDocletOptions).apply {
        addStringOption("Xdoclint:none", "-quiet")
        encoding = "UTF-8"
    }
}
